steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/codegen-ai-479819/codegen-backend', '-f', 'docker/backend/Dockerfile', '.']

images:
  - 'gcr.io/codegen-ai-479819/codegen-backend'
