steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/codegen-ai-479819/airflow', '-f', 'docker/airflow/Dockerfile', '.']
    timeout: 1200s
images:
  - 'gcr.io/codegen-ai-479819/airflow'
timeout: 1800s
